apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mydata-snapshot1
  namespace: sc13busybox
  labels:
    app.kubernetes.io/name: scenario13
    app: busybox
spec:
  volumeSnapshotClassName: csi-snap-class
  source:
    persistentVolumeClaimName: mydata
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mydata-snapshot2
  namespace: sc13busybox
  labels:
    app.kubernetes.io/name: scenario13
    app: busybox
spec:
  volumeSnapshotClassName: csi-snap-class
  source:
    persistentVolumeClaimName: mydata
