apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ontaplimit-5
  labels:
      scenario: ontap
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: storage-class-nfs