apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-tenant1
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  storagePools: "tenant1:aggr1"
allowVolumeExpansion: true
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-tenant2
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  storagePools: "tenant2:aggr2"
allowVolumeExpansion: true
