apiVersion: v1
kind: Secret
metadata:
  name: secret-snap-reserve
  namespace: trident
type: Opaque
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-snap-reserve
  namespace: trident
spec:
  version: 1
  backendName: nas-snap-reserve
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.133
  storagePrefix: sr_
  defaults:
    snapshotDir: 'true'     # using this parameter may cause issues with Centos8/RHEL8 as the .snapshot file-system is readonly
    snapshotPolicy: default
    snapshotReserve: '40'
  credentials:
    name: secret-snap-reserve