apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: ghost
  labels:
    app.kubernetes.io/name: scenario04
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scenario04
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scenario04
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: blog
        image: registry.demo.netapp.com/ghost:2.6-alpine
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http://192.168.0.63:30080
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: content
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: blog-content
