apiVersion: v1
kind: Namespace
metadata:
  name: resize
---
apiVersion: v1
kind: Secret
metadata:
  name: smbcreds
  namespace: resize
type: Opaque
stringData:
  username: DEMO\Administrator
  password: Netapp1!
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb
  namespace: resize
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: storage-class-smb
---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: resize
spec:
  nodeSelector:
    kubernetes.io/os: windows
  containers:
  - name: windowsserver
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    imagePullPolicy: IfNotPresent
    args:
    - powershell.exe
    - -Command
    - "Start-Sleep 360000"
    volumeMounts:
    - name: task-pv-storage
      mountPath: "C:\\Data"
      readOnly: false
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: pvc-smb