{
 "title": "Trident Protect Global view",
 "tags": [
  "24.10",
  "25.02",
  "25.06",
  "25.10"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Snapshots by status",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_customresource_snapshot_info) by (status)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backups by status",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_customresource_backup_info) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Snapshots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_customresource_snapshot_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Backups",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_customresource_backup_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last 10 Snapshots",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube_customresource_snapshot_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last 10 Backups",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kube_customresource_backup_info",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}