apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trident-configuration
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://192.168.0.65:3000/demo/scenario18'
    path: Infrastructure/Trident-Configuration
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: trident
  syncPolicy:
    automated:
      prune: false
      selfHeal: false