apiVersion: v1
kind: ResourceQuota
metadata:
  name: sc-resource-limit
  namespace: control
spec:
  hard:
    requests.storage: 10Gi
    storage-class-nfs.storageclass.storage.k8s.io/requests.storage: 8Gi
