apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secondary-pvc
  namespace: secondary
  annotations:
    trident.netapp.io/shareFromPVC: primary/primary-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: storage-class-nfs