{
 "title": "Trident Global Data 24.10",
 "description": "(starting with Trident 24.06)",
 "tags": [ "24.06" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Trident Version",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "trident_build_info" }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "trident_node_count" }
   ]
  },
  {
   "title": "Backends",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(trident_backend_count{backend_state=\"online\"})"
    }
   ]
  },
  {
   "title": "StorageClasses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "trident_storageclass_count" }
   ]
  },
  {
   "title": "PVC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(trident_volume_count)" }
   ]
  },
  {
   "title": "Snapshots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "trident_snapshot_count" }
   ]
  },
  {
   "title": "Capacity  provisioned by Trident (GB)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "trident_volume_total_bytes / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Capacity  mounted by Kubelet (GB)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes) / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Trident Backend Count per type",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "trident_backend_count{backend_state=\"online\"}"
    }
   ]
  },
  {
   "title": "Trident Management over Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "#PVC" }
   ],
   "targets": [
    { "expr": "sum(trident_volume_count)", "legendFormat": "#Volumes" },
    {
     "expr": "trident_volume_total_bytes / 1024 / 1024 / 1024",
     "legendFormat": "Capacity managed"
    }
   ]
  },
  {
   "title": "Number of volumes by Trident driver type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "trident_volume_count", "legendFormat": "{{backend_type}}" }
   ]
  },
  {
   "title": "Total Capacity by Trident driver type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "trident_volume_allocated_bytes / 1024 / 1024 / 1024",
     "legendFormat": "{{backend_type}}"
    }
   ]
  },
  {
   "title": "Trident Capacity per Backend Type (GB)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (trident_volume_allocated_bytes / 1024 / 1024 / 1024) by (backend_type)",
     "legendFormat": "{{backend_type}}"
    }
   ]
  },
  {
   "title": "Number of volumes per Backend Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (backend_type) (trident_volume_count)",
     "legendFormat": "{{backend_type}}"
    }
   ]
  },
  {
   "title": "Top10 Backend per Capacity (GB)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, trident_volume_allocated_bytes * on (backend_uuid) group_right trident_backend_info / 1024 / 1024 / 1024)",
     "legendFormat": "{{backend_name}}"
    }
   ]
  },
  {
   "title": "Top10 Number of volumes per Backend",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, trident_volume_count * on (backend_uuid) group_right trident_backend_info)",
     "legendFormat": "{{backend_name}}"
    }
   ]
  }
 ]
}