apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-qos1
provisioner: csi.trident.netapp.io
allowVolumeExpansion: true
parameters:
  backendType: "ontap-nas"
  selector: "performance=qos500iops"
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-qos2
provisioner: csi.trident.netapp.io
allowVolumeExpansion: true
parameters:
  backendType: "ontap-nas"
  selector: "performance=qos100MBps"
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-qos3
provisioner: csi.trident.netapp.io
allowVolumeExpansion: true
parameters:
  backendType: "ontap-nas"
  media: "ssd"
  selector: "performance=aQoS"