apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 5gb-1
  namespace: control
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: storage-class-nfs