kind: Pod
apiVersion: v1
metadata:
  name: busybox
  namespace: vsp
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: busybox
    image: registry.demo.netapp.com/busybox:1.35.0
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    volumeMounts:
    - mountPath: "/data/pvc1"
      name: pvc1
    - mountPath: "/data/pvc2"
      name: pvc2
    - mountPath: "/data/pvc3"
      name: pvc3
  volumes:
  - name: pvc1
    persistentVolumeClaim:
      claimName: pvc-vsp-1
  - name: pvc2
    persistentVolumeClaim:
      claimName: pvc-vsp-2
  - name: pvc3
    persistentVolumeClaim:
      claimName: pvc-vsp-3