apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-vsp1
  labels:
      scenario: vsp
provisioner: csi.trident.netapp.io
parameters:
  selector: "app=myapp1"
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-vsp2
  labels:
      scenario: vsp
provisioner: csi.trident.netapp.io
parameters:
  selector: "app=myapp2"
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-vsp3
  labels:
      scenario: vsp
provisioner: csi.trident.netapp.io
parameters:
  selector: "app=myapp3"