apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: ghost
  labels:
    app.kubernetes.io/name: scenario04
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: scenario04
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368
    nodePort: 30080