apiVersion: v1
kind: ServiceAccount
metadata:
  name: protect-user-secret
  namespace: pg
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: protect-user
  name: protect-user-secret
  namespace: pg
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bbox-tenant-rolebinding
  namespace: pg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trident-protect-tenant-cluster-role
subjects:
- kind: ServiceAccount
  name: protect-user
  namespace: pg