apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: alpine-vm1
  namespace: share
spec:
  runStrategy: Always
  template:
    spec:
      domain:
        cpu:
          cores: 1
        resources:
          requests:
            memory: 512Mi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          filesystems:
            - name: config-fs
              virtiofs: {}
            - name: shared-fs
              virtiofs: {}
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: alpine-boot-vm1
        - name: config-fs
          configMap:
            name: shared-config
        - name: shared-fs
          persistentVolumeClaim:
            claimName: shared-nfs
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              runcmd:
                - echo "alpine:alpine" | chpasswd
                - echo 'Welcome to alpine-vm1 (VirtioFS sharing) in the NetApp LoD!' > /etc/motd
                - apk add --no-cache lsblk nfs-utils
                - modprobe virtiofs || true
                - mkdir -p /mnt/config /mnt/shared
                - mount -t virtiofs config-fs /mnt/config
                - mount -t virtiofs shared-fs /mnt/shared
                - echo "config-fs /mnt/config virtiofs defaults 0 0" >> /etc/fstab
                - echo "shared-fs /mnt/shared virtiofs defaults 0 0" >> /etc/fstab
