apiVersion: v1
kind: Secret
metadata:
  name: sc24-credentials-vsadmin
  namespace: trident
type: Opaque
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tmr-src
  namespace: trident
spec:
  version: 1
  backendName: tmr-src
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.133
  storagePrefix: tmr1_
  autoExportCIDRs:
  - 192.168.0.0/24
  autoExportPolicy: true
  credentials:
    name: sc24-credentials-vsadmin
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-mirror-src
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  storagePools: "tmr-src:aggr1"
  trident.netapp.io/replication: "true"
allowVolumeExpansion: true
---
apiVersion: v1
kind: Secret
metadata:
  name: sc24-credentials-trident
  namespace: trident
type: Opaque
stringData:
  username: trident
  password: Netapp1!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tmr-dst
  namespace: trident
spec:
  version: 1
  backendName: tmr-dst
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.140
  replicationPolicy: MirrorAllSnapshots
  replicationSchedule: "5min"
  storagePrefix: tmr2_
  autoExportCIDRs:
  - 192.168.0.0/24
  autoExportPolicy: true
  credentials:
    name: sc24-credentials-trident
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-mirror-dst
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  storagePools: "tmr-dst:aggr1"
  trident.netapp.io/replication: "true"
allowVolumeExpansion: true