apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sc-nas-eco
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-nas-economy
