apiVersion: v1
kind: Secret
metadata:
  name: sc15-sp
  namespace: trident
type: Opaque
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: sc15-sp-tbc1
  namespace: trident
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.133
  backendName: Sc15SpTBC1
  nasType: nfs
  autoExportCIDRs:
  - 192.168.0.0/24
  autoExportPolicy: true
  credentials:
    name: sc15-sp
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: sc15-sp-tbc2
  namespace: trident
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.133
  backendName: Sc15SpTBC2
  nasType: nfs
  autoExportCIDRs:
  - 192.168.0.0/24
  autoExportPolicy: true
  credentials:
    name: sc15-sp
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc15-sp
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  storagePools: "Sc15SpTBC1:.*"
allowVolumeExpansion: true