apiVersion: v1
kind: Service
metadata:
  name: blog-vc1
  labels:
    app.kubernetes.io/name: sc21_vc1
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: sc21_vc1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368