kind: Pod
apiVersion: v1
metadata:
  name: my-app
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - name: my-frontend
      image: registry.demo.netapp.com/busybox:1.35.0
      volumeMounts:
      - mountPath: "/scratch"
        name: scratch-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: scratch-volume
      ephemeral:
        volumeClaimTemplate:
          metadata:
            labels:
              type: my-frontend-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "storage-class-nfs"
            resources:
              requests:
                storage: 1Gi