---
apiVersion: v1
kind: Namespace
metadata:
  name: tpsc05busybox
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydata1
  namespace: tpsc05busybox
  labels:
    app: busybox
    volume: mydata1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydata2
  namespace: tpsc05busybox
  labels:
    app: busybox
    volume: mydata2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: tpsc05busybox
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tpsc05busybox
      app: busybox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tpsc05busybox
        app: busybox
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: busybox
        image: registry.demo.netapp.com/busybox:1.35.0
        imagePullPolicy: IfNotPresent
        command: ['sleep', '3600']        
        volumeMounts:
        - mountPath: /data1
          name: volume1
        - mountPath: /data2
          name: volume2
      volumes:
      - name: volume1
        persistentVolumeClaim:
          claimName: mydata1
      - name: volume2
        persistentVolumeClaim:
          claimName: mydata2
