apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-content-nvme
  namespace: ghost-nvme
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: storage-class-nvme