apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-eco-limit
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas-economy"
  storagePools: "nas-eco-limit-poolsize:aggr1"