apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-content-iscsi
  namespace: ghost-iscsi-luks
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: storage-class-iscsi-luks