apiVersion: v1
kind: Service
metadata:
  name: blog-tenant1
  labels:
    app.kubernetes.io/name: sc21_tenant1
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: sc21_tenant1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368