apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-tenant1
  labels:
    app.kubernetes.io/name: sc21_tenant1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sc21_tenant1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sc21_tenant1
    spec:
      containers:
      - name: blog
        image: registry.demo.netapp.com/ghost:2.6-alpine
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http://GHOST_SERVICE_IP
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: content
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: blog-content-tenant1