apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secondary-pvc
  namespace: cnvc-secondary
  annotations:
    trident.netapp.io/cloneFromPVC: primary-pvc
    trident.netapp.io/cloneFromNamespace: cnvc-primary
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: storage-class-nfs