{
 "title": "Trident Debugging",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Trident Operation Duration Sum (5m)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(trident_ontap_operation_duration_in_milliseconds_by_svm_sum[5m])",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Trident Operation Duration Count",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "trident_ontap_operation_duration_in_milliseconds_by_svm_count",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Trident Operation Duration Sum (5m)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(trident_operation_duration_milliseconds_sum[5m])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Trident Operation Duration Count (ms)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "trident_operation_duration_milliseconds_count",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}