apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mydata-snapshot
  namespace: ghost
  labels:
    app.kubernetes.io/name: scenario13
    app: blog
spec:
  volumeSnapshotClassName: csi-snap-class
  source:
    persistentVolumeClaimName: mydata