apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-san-secured2
  namespace: trident
spec:
  version: 1
  backendName: svm-secured-iscsi
  storageDriverName: ontap-san
  managementLIF: 192.168.0.230
  storagePrefix: sec2_
  useCHAP: true
  credentials:
    name: ontap-iscsi-secured-secret