apiVersion: v1
kind: Namespace
metadata:
  name: ghost-san-secured
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-content-san
  namespace: ghost-san-secured
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: sc-svm-secured-san
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-san
  namespace: ghost-san-secured
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-san
  template:
    metadata:
      labels:
        app: blog-san
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: blog
        image: registry.demo.netapp.com/ghost:2.6-alpine
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http://my-blog.com
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: content
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: blog-content-san
---
apiVersion: v1
kind: Service
metadata:
  name: blog-san
  namespace: ghost-san-secured
spec:
  type: NodePort
  selector:
    app: blog-san
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368
    nodePort: 30981