apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-svm-secured-san
provisioner: csi.trident.netapp.io
allowVolumeExpansion: true
parameters:
  backendType: "ontap-san"
  storagePools: "svm-secured-iscsi:aggr1"
mountOptions:
   - discard