apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogimport
  labels:
    app: blogimport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogimport
  template:
    metadata:
      labels:
        app: blogimport
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: blog
        image: registry.demo.netapp.com/ghost:2.6-alpine
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http://192.168.0.63:30082
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: content
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: blog-content-import
