---
apiVersion: v1
kind: Namespace
metadata:
  name: sc07bbox1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydata1
  namespace: sc07bbox1
  labels:
    category: tmp
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydata2
  namespace: sc07bbox1
  labels:
    category: toprotect
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: storage-class-nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: sc07bbox1
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sc07bbox1
      app: busybox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sc07bbox1
        app: busybox
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: busybox
        image: registry.demo.netapp.com/busybox:1.35.0
        imagePullPolicy: IfNotPresent
        command: ['sleep', '3600']        
        volumeMounts:
        - mountPath: /mydata1
          name: volume1
        - mountPath: /mydata2
          name: volume2
      volumes:
      - name: volume1
        persistentVolumeClaim:
          claimName: mydata1
      - name: volume2
        persistentVolumeClaim:
          claimName: mydata2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: protect-user-secret
  namespace: sc07bbox1
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: protect-user
  name: protect-user-secret
  namespace: sc07bbox1
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bbox-tenant-rolebinding
  namespace: sc07bbox1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trident-protect-tenant-cluster-role
subjects:
- kind: ServiceAccount
  name: protect-user
  namespace: sc07bbox1
