kind: Pod
apiVersion: v1
metadata:
  name: busybox-br
spec:
  volumes:
    - name: volume
      persistentVolumeClaim:
       claimName: mydata2
  containers:
    - name: debugger
      image: busybox:1.35.0
      imagePullPolicy: IfNotPresent
      command: ['sleep', '3600']
      volumeMounts:
        - mountPath: "/data"
          name: volume
  nodeSelector:
    kubernetes.io/os: linux