apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-smb
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  nasType: "smb"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: ${pvc.namespace}
allowVolumeExpansion: true