apiVersion: v1
kind: Secret
metadata:
  name: secret-iscsi-svm-creds
  namespace: trident
type: Opaque
stringData:
  username: vsadmin
  password: Netapp1!
  chapInitiatorSecret: cl9qxWfnUFoinvk
  chapTargetInitiatorSecret: rwbwtuigONgbw
  chapTargetUsername: iJF4sgjrnwOwQ
  chapUsername: uh2a1io325bFFILn