apiVersion: v1
kind: Namespace
metadata:
  name: primary
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: primary-pvc
  namespace: primary
  annotations:
    trident.netapp.io/shareToNamespace: secondary
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: storage-class-nas
---

apiVersion: v1
kind: Pod
metadata: 
  name: busybox-primary
  namespace: primary
spec:
  containers:
  - name: busybox
    image: busybox:1.35
    args:
     - sleep
     - "infinity"
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: "/mnt/sharedvolume"
      name: nas-volume
  volumes:
    - name: nas-volume
      persistentVolumeClaim:
        claimName: primary-pvc