apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-content
  namespace: blog-scenario18
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: argocd-storage-class-nfs