apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: blog-scenario18
spec:
  type: NodePort
  selector:
    app: blog
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368
    nodePort: 30080