apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: alpine-vm
spec:
  runStrategy: Always
  template:
    spec:
      domain:
        cpu:
          cores: 1
        resources:
          requests:
            memory: 128Mi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: alpine-boot
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              runcmd:
                - echo "alpine:alpine" | chpasswd
                - echo 'Welcome to Alpine Linux on KubeVirt in the NetApp LoD!' > /etc/motd
                - apk add --no-cache lsblk parted