---
- hosts: localhost
  collections:
    - netapp.ontap

  vars:
    ontap_parameters: &ontap_parameters
      hostname: "{{ hostname }}" 
      username: "{{ username }}" 
      password: "{{ password }}"
      https: true
      validate_certs: false

  name: Secured SVM Network Management
  tasks:
  - name: Create Service Policy for Management (Core)
    netapp.ontap.na_ontap_command:
      command: ['network', 'interface', 'service-policy', 'create', '-policy', 'secured_management', '-vserver', 'svm_secured',  '-allowed-addresses', '192.168.0.61/32,192.168.0.62/32,192.168.0.63/32', '-service', 'data-core']
      privilege: "advanced"
      <<: *ontap_parameters

  - name: Create Service Policy for Management (HTTPS)
    netapp.ontap.na_ontap_command:
      command: ['network', 'interface', 'service-policy', 'add-service', '-policy', 'secured_management', '-vserver', 'svm_secured',  '-allowed-addresses', '192.168.0.61/32,192.168.0.62/32,192.168.0.63/32', '-service', 'management-https']
      privilege: "advanced"
      <<: *ontap_parameters

  - name: Create Service Policy for NFS (Core)
    netapp.ontap.na_ontap_command:
      command: ['network', 'interface', 'service-policy', 'create', '-policy', 'secured_nfs', '-vserver', 'svm_secured',  '-allowed-addresses', '0.0.0.0/0', '-service', 'data-core']
      privilege: "advanced"      
      <<: *ontap_parameters

  - name: Create Service Policy for NFS (Data)
    netapp.ontap.na_ontap_command:
      command: ['network', 'interface', 'service-policy', 'add-service', '-policy', 'secured_nfs', '-vserver', 'svm_secured',  '-allowed-addresses', '0.0.0.0/0', '-service', 'data-nfs']
      privilege: "advanced"      
      <<: *ontap_parameters

  - name: Create Service Policy for iSCSI (Core)
    netapp.ontap.na_ontap_command:
      command: ['network', 'interface', 'service-policy', 'create', '-policy', 'secured_iscsi', '-vserver', 'svm_secured',  '-allowed-addresses', '0.0.0.0/0', '-service', 'data-core']
      privilege: "advanced"      
      <<: *ontap_parameters

  - name: Create Service Policy for iSCSI (Data)
    netapp.ontap.na_ontap_command:
      command: ['network', 'interface', 'service-policy', 'add-service', '-policy', 'secured_iscsi', '-vserver', 'svm_secured',  '-allowed-addresses', '0.0.0.0/0', '-service', 'data-iscsi']
      privilege: "advanced"      
      <<: *ontap_parameters

  - name: Create Mgmt Interface
    netapp.ontap.na_ontap_interface:
      state: present
      interface_name: secured_mgmt
      home_port: e0c
      home_node: cluster1-01
      admin_status: up
      service_policy: secured_management
      address: 192.168.0.230
      netmask: 255.255.255.0
      vserver: svm_secured
      <<: *ontap_parameters

  - name: Create NFS Interface
    netapp.ontap.na_ontap_interface:
      state: present
      interface_name: secured_nfs
      home_port: e0d
      home_node: cluster1-01
      admin_status: up
      service_policy: secured_nfs
      address: 192.168.0.231
      netmask: 255.255.255.0
      vserver: svm_secured
      <<: *ontap_parameters

  - name: Create iSCSI Interface
    netapp.ontap.na_ontap_interface:
      state: present
      interface_name: secured_iscsi
      home_port: e0d
      home_node: cluster1-01
      admin_status: up
      service_policy: secured_iscsi
      address: 192.168.0.232
      netmask: 255.255.255.0
      vserver: svm_secured
      <<: *ontap_parameters