apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydata-iscsi
  namespace: scenario28
  labels:
    app.kubernetes.io/name: scenario28
    app: bbox-iscsi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-iscsi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-iscsi
  namespace: scenario28
  labels:
    app.kubernetes.io/name: scenario28
    app: bbox-iscsi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scenario28
      app: bbox-iscsi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scenario28
        app: bbox-iscsi
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: busybox
        image: registry.demo.netapp.com/busybox:1.35.0
        imagePullPolicy: IfNotPresent
        command: ['sleep', '3600']        
        volumeMounts:
        - mountPath: /data
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: mydata-iscsi
