apiVersion: protect.trident.netapp.io/v1
kind: Schedule
metadata:
  name: wordpress-mysql
  namespace: wpargo1
spec:
  appVaultRef: ontap-vault
  applicationRef: wordpress-mysql
  backupRetention: "12"
  dataMover: Kopia
  enabled: true
  granularity: Custom
  recurrenceRule: |-
    DTSTART:20250106T000100Z
    RRULE:FREQ=MINUTELY;INTERVAL=5
  snapshotRetention: "6"