apiVersion: protect.trident.netapp.io/v1
kind: Application
metadata:
  name: wordpress-mysql
  namespace: wpargo1
spec:
  includedNamespaces:
    - labelSelector:
        matchLabels:
          tier: mysql
      namespace: wpargo1