---
apiVersion: v1
kind: Namespace
metadata:
  name: sc13busybox
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydata
  namespace: sc13busybox
  labels:
    app.kubernetes.io/name: sc13busybox
    app: busybox
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-nas-economy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: sc13busybox
  labels:
    app.kubernetes.io/name: sc13busybox
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sc13busybox
      app: busybox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sc13busybox
        app: busybox
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: busybox
        image: registry.demo.netapp.com/busybox:1.35.0
        imagePullPolicy: IfNotPresent
        command: ['sleep', '3600']        
        volumeMounts:
        - mountPath: /data
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: mydata
