kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbench-pvc-qos2
spec:
  storageClassName: sc-qos2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dbench-qos2
spec:
  template:
    spec:
      containers:
      - name: dbench-qos2
        image: ndrpnt/dbench:1.0.0
        env:
          - name: DBENCH_MOUNTPOINT
            value: /data
          # - name: DBENCH_QUICK
          #   value: "yes"
          # - name: FIO_SIZE
          #   value: 1G
          # - name: FIO_OFFSET_INCREMENT
          #   value: 256M
          # - name: FIO_DIRECT
          #   value: "0"
        volumeMounts:
        - name: dbench-pv
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: dbench-pv
        persistentVolumeClaim:
          claimName: dbench-pvc-qos2
  backoffLimit: 4