{
 "title": "Trident_20.01",
 "description": "(deprecated with Trident 20.10)",
 "tags": [
  "20.01",
  "20.04",
  "20.07"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Overall counters",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "trident_core_snapshot_count", "legendFormat": "# Snapshots" },
    {
     "expr": "trident_core_storage_class_count",
     "legendFormat": "# Storage Classes"
    },
    {
     "expr": "trident_core_backend_count_by_state{state=\"online\"}",
     "legendFormat": "# Backends"
    },
    { "expr": "trident_core_node_count", "legendFormat": "# Nodes" }
   ]
  },
  {
   "title": "Trident Backend Count per type",
   "type": "table-old",
   "description": "This counter includes failed backends",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "trident_core_backend_count_by_type"
    }
   ]
  },
  {
   "title": "# Volumes currently managed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(trident_core_volume_count)" }
   ]
  },
  {
   "title": "Trident Management over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "#PVC" }
   ],
   "targets": [
    { "expr": "SUM(trident_core_volume_count)", "legendFormat": "#Volumes" },
    {
     "expr": "trident_core_volume_total_bytes / 1024 / 1024 / 1024",
     "legendFormat": "Capacity managed"
    }
   ]
  },
  {
   "title": "Capacity currently managed (GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "trident_core_volume_total_bytes / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Number of volumes by Trident driver type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "trident_core_volume_count_by_backend",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Total Capacity by Trident driver type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "trident_core_volume_total_bytes_by_backend / 1024 / 1024 / 1024",
     "legendFormat": "{{backend}}"
    }
   ]
  }
 ]
}