apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-nfs
  namespace: trident
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.133
  dataLIF: 192.168.0.131
  backendName: BackendForNFS
  nasType: nfs
  autoExportCIDRs:
  - 192.168.0.0/24
  autoExportPolicy: true
  svm: nassvm
  credentials:
    name: secret-nas-svm-creds