apiVersion: v1
kind: Namespace
metadata:
  name: harvest
---
apiVersion: v1
kind: Endpoints
metadata:
  name: harvest-metrics
  namespace: harvest
  labels:
    app: harvest-metrics
subsets:
  - addresses:
      - ip: 192.168.0.69
    ports:
      - name: metrics
        port: 31000
---  
apiVersion: v1
kind: Service
metadata:
  name: harvest-metrics
  namespace: harvest
  labels:
    app: harvest-metrics
spec:
    type: ClusterIP
    ports:
    - name: metrics
      port: 9000
      targetPort: 31000
--- 
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: harvest-metrics
  namespace: monitoring
  labels:
    app: harvest-metrics
    release: prom-operator
spec:
  selector:
    matchLabels:
      app: harvest-metrics
  namespaceSelector:
    matchNames:
    - harvest
  endpoints:
  - port: metrics
    interval: 10s