apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-content-tenant1
  labels:
    app.kubernetes.io/name: sc21_tenant1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: sc-tenant1