kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: blog-content-tenant1-from-snap
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: sc-tenant1
  dataSource:
    name: blog-content-tenant1-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io