apiVersion: v1
kind: Namespace
metadata:
  name: resize
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-to-resize-nfs
  namespace: resize
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: storage-class-nfs
---
kind: Pod
apiVersion: v1
metadata:
  name: busyboxnfs
  namespace: resize
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - name: busybox
      image: registry.demo.netapp.com/busybox:1.35.0
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      volumeMounts:
        - mountPath: "/data"
          name: nfsstorage
  volumes:
    - name: nfsstorage
      persistentVolumeClaim:
       claimName: pvc-to-resize-nfs