apiVersion: v1
kind: Secret
metadata:
  name: secret-nametemplate
  namespace: trident
type: Opaque
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: tbc-nametemplate
  namespace: trident
spec:
  version: 1
  backendName: nametemplate
  storageDriverName: ontap-nas
  storagePrefix: lod
  managementLIF: 192.168.0.133
  defaults:
    nameTemplate: "{{ .config.StoragePrefix }}_{{ .volume.Namespace }}_{{ .volume.RequestName }}"
  credentials:
    name: secret-nametemplate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-nametemplate
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  storagePools: "nametemplate:.*"
---
apiVersion: v1
kind: Namespace
metadata:
  name: nametemplate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: nametemplate
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: sc-nametemplate