apiVersion: v1
kind: Secret
metadata:
  name: secret-labeltemplate
  namespace: trident
type: Opaque
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: tbc-labeltemplate
  namespace: trident
spec:
  version: 1
  backendName: labeltemplate
  storageDriverName: ontap-nas
  storagePrefix: lod_
  managementLIF: 192.168.0.133
  labels: {"cluster": "LoD", "Namespace": "{{.volume.Namespace}}", "PVC": "{{.volume.RequestName}}"}
  credentials:
    name: secret-labeltemplate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-labeltemplate
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  storagePools: "labeltemplate:.*"
---
apiVersion: v1
kind: Namespace
metadata:
  name: labeltemplate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: labeltemplate
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: sc-labeltemplate