version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.14.2
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      #- GITEA__server__DOMAIN=demo.netapp.com
      #- GITEA__server__SSH_DOMAIN=demo.netapp.com
      #- GITEA__server__ROOT_URL=http://gitea.demo.netapp.com:3000
      - GITEA__server__DOMAIN=192.168.0.65
      - GITEA__server__SSH_DOMAIN=192.168.0.65
      - GITEA__server__ROOT_URL=http://192.168.0.65:3000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__picture__DISABLE_GRAVATAR=true
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:8.0.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql