apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-content-vc2
  labels:
    app.kubernetes.io/name: sc21_vc2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: sc-tenant2