apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-content-san
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: storage-class-san