apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://192.168.0.65:3000/demo/wordpress'
    path: Wordpress_Snapshot/App_config
    targetRevision: master
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wpargo1
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true