apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-content-vc1
  labels:
    app.kubernetes.io/name: sc21_vc1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: sc_vc1