apiVersion: v1
kind: Service
metadata:
  name: win-webserver
  namespace: webserver
  labels:
    app: win-webserver
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: win-webserver
  type: LoadBalancer