apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc3
  labels:
    app.kubernetes.io/name: test3
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-nfs
