apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc5
  labels:
    app.kubernetes.io/name: test5
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-nfs
