apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-smb
  namespace: trident
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.133
  dataLIF: 192.168.0.131
  backendName: BackendForSMB
  nasType: smb
  svm: nassvm
  securityStyle: ntfs
  unixPermissions: ""
  credentials:
    name: secret-nas-svm-creds