apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-nas-economy
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas-economy"
  storagePools: "BackendForNFSQtrees:aggr1"
allowVolumeExpansion: true
