global:
  defaultStorageClass: storage-class-nfs

wordpressUsername: admin
wordpressPassword: demolod
wordpressBlogName: "demo RWX and NFS"
replicaCount: 2

nodeSelector: 
  kubernetes.io/os: linux

image:
  tag: 6.6.1-debian-12-r3

persistence:
  accessModes: 
    - ReadWriteMany

resources:
  requests:
    memory: 256Mi
    cpu: 200m

mariadb:
  image:
    tag: 11.4.2-debian-12-r2