apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot1
spec:
  volumeSnapshotClassName: csi-snap-class
  source:
    persistentVolumeClaimName: pvc-to-snap
---

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot2
spec:
  volumeSnapshotClassName: csi-snap-class
  source:
    persistentVolumeClaimName: pvc-to-snap
---

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot3
spec:
  volumeSnapshotClassName: csi-snap-class
  source:
    persistentVolumeClaimName: pvc-to-snap