apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-iscsi-economy
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san-economy"
  fsType: "ext4"
mountOptions:
   - discard
allowVolumeExpansion: true