apiVersion: v1
kind: Namespace
metadata:
  name: resize
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-to-resize-iscsi
  namespace: resize
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: storage-class-iscsi
---
kind: Pod
apiVersion: v1
metadata:
  name: busyboxiscsi
  namespace: resize
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - name: busybox
      image: registry.demo.netapp.com/busybox:1.35.0
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      volumeMounts:
        - mountPath: "/data"
          name: blockstorage
  volumes:
    - name: blockstorage
      persistentVolumeClaim:
       claimName: pvc-to-resize-iscsi