apiVersion: v1
kind: Namespace
metadata:
  name: vgs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydata1
  namespace: vgs
  labels:
    app: busybox
    consistencygroup: group1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-iscsi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydata2
  namespace: vgs
  labels:
    app: busybox
    consistencygroup: group1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-iscsi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: vgs
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vgs
      app: busybox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vgs
        app: busybox
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: busybox
        image: registry.demo.netapp.com/busybox:1.35.0
        imagePullPolicy: IfNotPresent
        command: ['sleep', '3600']        
        volumeMounts:
        - mountPath: /data1
          name: volume1
        - mountPath: /data2
          name: volume2
      volumes:
      - name: volume1
        persistentVolumeClaim:
          claimName: mydata1
      - name: volume2
        persistentVolumeClaim:
          claimName: mydata2