apiVersion: v1
kind: Service
metadata:
  name: blogclone
  namespace: ghost
  labels:
    app.kubernetes.io/name: scenario13
    app: blogclone
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: scenario13
    app: blogclone
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368
    nodePort: 30081