apiVersion: v1
kind: Namespace
metadata:
  name: my-alpine5
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: datavolume-clone-source-reader
  namespace: vm-templates
rules:
  - apiGroups:
      - cdi.kubevirt.io
    resources:
      - datavolumes/source
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-my-alpine5-datavolume-clone
  namespace: vm-templates
subjects:
  - kind: ServiceAccount
    name: default
    namespace: my-alpine5
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: datavolume-clone-source-reader