apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  tridentImage: registry.demo.netapp.com/trident:24.06.1
  autosupportImage: registry.demo.netapp.com/trident-autosupport:24.06.1
  imagePullPolicy: IfNotPresent
  windows: false
  silenceAutosupport: true