apiVersion: v1
kind: Secret
metadata:
  name: ontap-cluster-secret-username
  namespace: trident
type: Opaque
stringData:
  username: admin
  password: Netapp1!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-limit-aggr
  namespace: trident
spec:
  version: 1
  backendName: nas-limit-aggr
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.101
  limitAggregateUsage: 30%
  svm: nassvm
  defaults:
    spaceReserve: volume
  credentials:
    name: ontap-cluster-secret-username
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sclimitaggr
provisioner: csi.trident.netapp.io
parameters:
   storagePools: "nas-limit-aggr:aggr1"