apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-limit-poolsize
  namespace: trident
spec:
  version: 1
  backendName: nas-limit-poolsize
  storageDriverName: ontap-nas-economy
  managementLIF: 192.168.0.133
  limitVolumePoolSize: 5g
  credentials:
    name: secret-nas-svm-creds
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sclimitpoolsize
provisioner: csi.trident.netapp.io
parameters:
   storagePools: "nas-limit-poolsize:aggr1"