apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: trident
spec:
  provider:
    vault:
      server: http://vault.vault.svc:8200
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trident-ontap-credentials
  namespace: trident
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: secret-nas-svm-vault
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: trident/ontap
      property: username
  - secretKey: password
    remoteRef:
      key: trident/ontap
      property: password
