apiVersion: v1
kind: Secret
metadata:
  name: secret-topo
  namespace: trident
type: Opaque
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-east
  namespace: trident
spec:
  version: 1
  backendName: nas-east
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.133
  storagePrefix: east_
  credentials:
    name: secret-topo
  supportedTopologies:
    - topology.kubernetes.io/region: east
    - topology.kubernetes.io/zone: east1
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-west
  namespace: trident
spec:
  version: 1
  backendName: nas-west
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.133
  storagePrefix: west_
  credentials:
    name: secret-topo
  supportedTopologies:
    - topology.kubernetes.io/region: west
    - topology.kubernetes.io/zone: west1