apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-nas-snap-reserve
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  storagePools: "nas-snap-reserve:aggr1"
