apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: argocd-storage-class-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"