{
 "title": "Trident Volume Details",
 "tags": [
  "21.04",
  "21.07",
  "21.10",
  "22.01",
  "22.04",
  "22.07"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(volume_labels, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(volume_labels{datacenter=\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(volume_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}, svm)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   },
   {
    "name": "namespace",
    "query": {
     "query": "kube_persistentvolumeclaim_info{}"
    }
   },
   {
    "name": "pvc",
    "query": {
     "query": "kube_persistentvolumeclaim_info{namespace=\"$namespace\"}"
    }
   },
   {
    "name": "uuid1",
    "query": {
     "query": "kube_persistentvolumeclaim_info{namespace=\"$namespace\",persistentvolumeclaim=\"$pvc\"}"
    }
   },
   {
    "name": "uuid2",
    "query": {
     "query": "kube_persistentvolumeclaim_info{namespace=\"$namespace\",persistentvolumeclaim=\"$pvc\"}"
    }
   },
   {
    "name": "uuid3",
    "query": {
     "query": "kube_persistentvolumeclaim_info{namespace=\"$namespace\",persistentvolumeclaim=\"$pvc\"}"
    }
   },
   {
    "name": "uuid4",
    "query": {
     "query": "kube_persistentvolumeclaim_info{namespace=\"$namespace\",persistentvolumeclaim=\"$pvc\"}"
    }
   },
   {
    "name": "uuid5",
    "query": {
     "query": "kube_persistentvolumeclaim_info{namespace=\"$namespace\",persistentvolumeclaim=\"$pvc\"}"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(volume_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",volume=~\".*_pvc_$uuid1.$uuid2.$uuid3.$uuid4.$uuid5.*\"}, volume)"
    }
   },
   {
    "name": "Aggregate",
    "query": {
     "query": "label_values(volume_labels{volume=\"$Volume\"},aggr)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(volume_labels{volume=\"$Volume\"},node)"
    }
   },
   {
    "name": "pv",
    "query": {
     "query": "kube_persistentvolumeclaim_info{namespace=\"$namespace\",persistentvolumeclaim=\"$pvc\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview of $pvc ⟶ $Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "volume_size{aggr=\"$Aggregate\",cluster=\"$Cluster\",datacenter=\"$Datacenter\",volume=\"$Volume\"}"
    }
   ]
  },
  {
   "title": "Used by data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "volume_space_logical_used{aggr=\"$Aggregate\",cluster=\"$Cluster\",datacenter=\"$Datacenter\",volume=\"$Volume\"}"
    }
   ]
  },
  {
   "title": "Available for data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "volume_size_available{aggr=\"$Aggregate\",cluster=\"$Cluster\",datacenter=\"$Datacenter\",volume=\"$Volume\"}"
    }
   ]
  },
  {
   "title": "Data percent full",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "volume_space_logical_used_percent{aggr=\"$Aggregate\",cluster=\"$Cluster\",datacenter=\"$Datacenter\",volume=\"$Volume\"}"
    }
   ]
  },
  {
   "title": "PVC Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes{persistentvolumeclaim=\"$pvc\"}"
    }
   ]
  },
  {
   "title": "Used by snapshots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "volume_snapshots_size_used{aggr=\"$Aggregate\",cluster=\"$Cluster\",datacenter=\"$Datacenter\",volume=\"$Volume\"}"
    }
   ]
  },
  {
   "title": "Snapshot reserve available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "volume_snapshot_reserve_available{aggr=\"$Aggregate\",cluster=\"$Cluster\",datacenter=\"$Datacenter\",volume=\"$Volume\"}"
    }
   ]
  },
  {
   "title": "Snapshot reserve full",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "volume_snapshot_reserve_used_percent{aggr=\"$Aggregate\",cluster=\"$Cluster\",datacenter=\"$Datacenter\",volume=\"$Volume\"}"
    }
   ]
  },
  {
   "title": "PVC overview",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_info{persistentvolumeclaim=\"$pvc\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Volume details",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "volume_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
    },
    {
     "expr": "volume_new_status{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
    },
    {
     "expr": "volume_size_total{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
    },
    {
     "expr": "volume_size_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}"
    }
   ]
  },
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Volume Average Latency",
   "type": "stat",
   "description": "Average Latency of top $TopResources volumes",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(topk($TopResources, volume_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}))/1000"
    }
   ]
  },
  {
   "title": "Volume Total Throughput",
   "type": "stat",
   "description": "Throughput of top $TopResources volumes",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(topk($TopResources, volume_write_data+volume_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}))"
    }
   ]
  },
  {
   "title": "Volume Total IOPs",
   "type": "stat",
   "description": "IOPs of top $TopResources volumes",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(topk($TopResources, volume_total_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}))"
    }
   ]
  },
  {
   "title": "Volume Top Average Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, volume_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
     "legendFormat": "{{svm}} / {{volume}}"
    }
   ]
  },
  {
   "title": "Volume Top Average Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, volume_write_data+volume_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Volume Top IOPs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "topk($TopResources, volume_total_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
     "legendFormat": "{{svm}} - {{volume}}"
    }
   ]
  },
  { "title": "Volume Table Drilldown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Kubernetes Volumes in Cluster",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "volume_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\".*pvc.*\"}"
    },
    {
     "expr": "volume_new_status{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\".*pvc.*\"}"
    },
    {
     "expr": "volume_size_total{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\".*pvc.*\"}"
    },
    {
     "expr": "volume_size_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\".*pvc.*\"}"
    },
    {
     "expr": "volume_sis_dedup_saved{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\".*pvc.*\"}"
    },
    {
     "expr": "volume_sis_compress_saved{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\".*pvc.*\"}"
    },
    {
     "expr": "volume_sis_dedup_saved+volume_sis_compress_saved{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\".*pvc.*\"}"
    },
    {
     "expr": "volume_space_logical_used{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\".*pvc.*\"}"
    },
    {
     "expr": "volume_space_physical_used{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\".*pvc.*\"}"
    }
   ]
  },
  {
   "title": "Top5 Kubernetes Volume Read Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "topk(5, volume_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\".*pvc.*\"})/1000",
     "legendFormat": "{{svm}} / {{volume}}"
    }
   ]
  },
  {
   "title": "Top5 Kubernetes Volume Read Throughput",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "topk(5, volume_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\".*pvc.*\"})",
     "legendFormat": "{{svm}} / {{volume}}"
    }
   ]
  },
  {
   "title": "Top5 Kubernetes Volume Read IOPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "topk(5, volume_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\".*pvc.*\"})",
     "legendFormat": "{{svm}} / {{volume}}"
    }
   ]
  },
  {
   "title": "Top5 Kubernetes Volume Write Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "topk(5, volume_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\".*pvc.*\"})/1000",
     "legendFormat": "{{svm}} / {{volume}}"
    }
   ]
  },
  {
   "title": "Top5 Kubernetes Volume Write Throughput",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "topk(5, volume_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\".*pvc.*\"})",
     "legendFormat": "{{svm}} / {{volume}}"
    }
   ]
  },
  {
   "title": "Top5 Kubernetes Volume Write IOPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "topk(5, volume_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\".*pvc.*\"})",
     "legendFormat": "{{svm}} / {{volume}}"
    }
   ]
  },
  {
   "title": "Volume WAFL Layer Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, volume_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Read Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, volume_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Read IOPs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, volume_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, volume_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Write Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, volume_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    },
    {
     "title": "Write IOPs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, volume_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} - {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top Volume End-to-End QoS Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "QoS Volume Read Latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_volume_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "QoS Volume Read Throughput",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_volume_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "QoS Volume Read IOPS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_volume_read_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "QoS Volume Write Latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_volume_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "QoS Volume Write Throughput",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_volume_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "QoS Volume Write IOPS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_volume_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "QoS Volume Sequential Reads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_volume_sequential_reads{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "QoS Volume Sequential Writes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_volume_sequential_writes{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"})",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top Volume QoS Resource Latency Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume Latency from Network",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"network\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volume Latency from Throttle",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"throttle\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volume Latency from Frontend",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"frontend\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volume Latency from Cluster",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"cluster\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volume Latency from Backend",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"backend\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volume Latency from Disk",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"disk\"})/1000",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Volume Latency from Suspend",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"suspend\"})/1000",
       "legendFormat": "{{svm}} / {{volume}} "
      }
     ]
    },
    {
     "title": "Volume Latency from Cloud",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"cloud\"})/1000",
       "legendFormat": "{{svm}} / {{volume}} "
      }
     ]
    },
    {
     "title": "Volume Latency from NVLog Mirroring",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk($TopResources, qos_detail_volume_resource_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\",resource=\"nvlog\"})/1000",
       "legendFormat": "{{svm}} / {{volume}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Top Volume Fabricpool Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true
  },
  {
   "title": "Per Volume Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Per Volume Space Used",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "decbytes", "label": "Used" }
     ],
     "targets": [
      {
       "expr": "volume_size{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Volume Total Size"
      },
      {
       "expr": "volume_space_physical_used{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Physical Space Used"
      },
      {
       "expr": "volume_space_logical_used{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Logical Space Used"
      },
      {
       "expr": "volume_size_used{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Volume Size Used"
      }
     ]
    },
    {
     "title": "Per Volume Space Used Percent",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "percent", "label": "%" }
     ],
     "targets": [
      {
       "expr": "volume_space_physical_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Physical Space Used"
      },
      {
       "expr": "volume_space_logical_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Logical Space Used"
      },
      {
       "expr": "volume_size_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Volume Size Used"
      }
     ]
    },
    {
     "title": "Per Volume Snapshot Space Used",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "decbytes", "label": "IOPs/TB" }
     ],
     "targets": [
      {
       "expr": "volume_snapshots_size_available{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Snapshot Size Available"
      },
      {
       "expr": "volume_snapshot_reserve_size{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Snapshot Reserve Size"
      },
      {
       "expr": "volume_snapshot_reserve_available{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Snapshot Reserve Available"
      },
      {
       "expr": "volume_snapshots_size_used{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Snapshot Size Used"
      }
     ]
    },
    {
     "title": "Per Volume Snapshot Space Used Percent",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "percent", "label": "%" }
     ],
     "targets": [
      {
       "expr": "volume_snapshot_reserve_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Snapshot Reserve"
      },
      {
       "expr": "volume_snapshot_reserve_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Snapshot Reserve Used"
      },
      {
       "expr": "volume_size_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume\"}",
       "legendFormat": "{{svm}} - {{volume}} - Volume Size Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Highlights for node $Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Disks",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count( count by(disk) (disk_labels{node=~\"$Node\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}) )"
      }
     ]
    },
    {
     "title": "Failed Disks",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count( count by(serial_number) (disk_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",failed=~\"true\"}) )"
      }
     ]
    },
    {
     "title": "Raid Groups",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 10, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count( count by(raid) (aggr_disk_busy{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}) )"
      }
     ]
    },
    {
     "title": "Plexes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 15, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count( count by(plex) (aggr_disk_busy{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}) )"
      }
     ]
    },
    {
     "title": "Disk Capacity per Aggregate",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aggr_raid_disk_count{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}"
      },
      {
       "expr": "aggr_space_total{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}"
      },
      {
       "expr": "aggr_space_used_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}"
      }
     ]
    },
    {
     "title": "Disk Utilization per Aggregate",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max by (node, aggr) (aggr_disk_total_transfers{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"})"
      },
      {
       "expr": "max by (node, aggr) (aggr_disk_busy{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "List of disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disks in aggregate $Aggregate on node $Node",
     "type": "table",
     "description": "Some Clusters don't report average latency, so the values might be 0s.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "disk_bytes_per_sector * disk_sectors{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}"
      },
      {
       "expr": "disk_stats_io_kbps{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}"
      },
      {
       "expr": "disk_stats_average_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}"
      },
      {
       "expr": "disk_uptime{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}"
      },
      {
       "expr": "label_join(disk_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}, \"diskStatus\", \" \",\"NonSupportedField\", \"outage\")"
      },
      {
       "expr": "label_join(aggr_disk_user_reads{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",aggr=\"$Aggregate\"}, \"Aggregate\", \" \", \"aggr\")"
      }
     ]
    }
   ]
  }
 ]
}