apiVersion: v1
kind: Namespace
metadata:
  name: sc19
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc19-pvc
  namespace: sc19
  labels:
    app.kubernetes.io/name: sc19RWXNFSFstype
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: storage-class-nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc19-rwo-iscsi
  namespace: sc19
  labels:
    app.kubernetes.io/name: sc19RWXNFSFstype
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sc19RWXNFSFstype
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sc19RWXNFSFstype
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
          fsGroup: 1001
          runAsUser: 1002
          runAsGroup: 1003
          #runAsNonRoot: true
      containers:
      - name: blog
        image: ghost:2.6-alpine
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http://192.168.0.63:31184
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: content
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: sc19-pvc
