apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: mydata-snapshot
  labels:
    app.kubernetes.io/name: scenario13
    app: busybox
spec:
  volumeSnapshotClassName: csi-snap-class
  source:
    persistentVolumeClaimName: mydata