apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc4
  labels:
    app.kubernetes.io/name: test4
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-nas
