apiVersion: protect.trident.netapp.io/v1
kind: Application
metadata:
  name: wordpress
  namespace: wpargo2
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  includedNamespaces:
    - namespace: wpargo2