apiVersion: v1
kind: Secret
metadata:
  name: secret-proxy
  namespace: trident
type: Opaque
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-proxy
  namespace: trident
spec:
  version: 1
  backendName: nas-proxy
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.63:8443
  dataLIF: 192.168.0.131
  storagePrefix: proxy_
  credentials:
    name: secret-proxy